tarea1/Conversor/urls.py
from django.urls import path
from .views import menu, hexadecimal_view, binary_view, octal_view, decimal_view, bases_to_binary, bases_to_hexadecimal, bases_to_octal, bases_to_decimal

app_name='conversor'

urlpatterns = [
    path('menu', menu, name='menu'),
    path('hexadecimal', hexadecimal_view, name='hexadecimal'),
    path('binario', binary_view, name='binario'),
    path('octal', octal_view, name='octal'),
    path('decimal', decimal_view, name='decimal'),
    
    path('bases_to_binary/<str:number>/<str:type>', bases_to_binary, name='bases_to_binary'),
    path('bases_to_hexadecimal/<str:number>/<str:type>', bases_to_hexadecimal, name='bases_to_hexadecimal'),
    path('bases_to_octal/<str:number>/<str:type>', bases_to_octal, name='bases_to_octal'),
    path('bases_to_decimal/<str:number>/<str:type>', bases_to_decimal, name='bases_to_decimal'),
]

tarea1/patrones/urls.py
from django.urls import path
from . import views

app_name='patrones'

urlpatterns = [
    path('',views.cargarArchivo, name='cargarArchivo'),
    path('resultados/<str:nombre>',views.mostrarResultados, name='resultados'),
    path('lista-archivos',views.lista_archivos, name='listaArchivos'),

]

tarea1/tarea1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patrones/',include('patrones.urls')),
    path('Conversor/',include('Conversor.urls')), 


]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tarea1/Conversor/models.py
from django.db import models

# Create your models here.

tarea1/patrones/models.py
from django.db import models

# Create your models here.

tarea1/Conversor/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json

# Vistas

def menu(request):
    return render(request, 'menu.html')

def hexadecimal_view(request):
    return render(request, 'hexadecimal.html')

def binary_view(request):
    return render(request, 'binario.html')

def octal_view(request):
    return render(request, 'octal.html')

def decimal_view(request):
    return render(request, 'decimal.html')


# Convertidores de bases: a binario

def bases_to_binary(request, number, type):
    
    # Convertir number a entero
    if type == 'hexadecimal':
        number = int(number, 16)
    elif type == 'octal':
        number = int(number, 8)
    else:
        number = int(number)
        
    # Convertir a binario
    binario = bin(number)
    
    #binario = '1010'
        
    binario = binario.split("b")[1]
    cadena = "Binario: {}".format(binario)
    partes = cadena.split(": ")
    diccionario = {partes[0].strip(): partes[1].strip()}
    return HttpResponse(json.dumps(diccionario), content_type="application/json")
   
# Convertidores de bases: a hexadecimal
def bases_to_hexadecimal(request, number, type):
    
    # Convertir number a entero
    if type == 'binario':
        number = int(number, 2)
    elif type == 'octal':
        number = int(number, 8)
    else:
        number = int(number)
        
    # Convertir a hexadecimal
    hexadecimal = hex(number)
    
    hexadecimal = hexadecimal.split("x")[1]
    cadena = "Hexadecimal: {}".format(hexadecimal)
    partes = cadena.split(": ")
    diccionario = {partes[0].strip(): partes[1].strip()}
    return HttpResponse(json.dumps(diccionario), content_type="application/json")

# Convertidores de bases: a octal
    # El constructor de los números octales es oct()
    
def bases_to_octal(request, number, type):
    
    # Convertir number a entero
    if type == 'binario':
        number = int(number, 2)
    elif type == 'hexadecimal':
        number = int(number, 16)
    else:
        number = int(number)
        
    # Convertir a octal
    octal = oct(number)
    
    octal = octal.split("o")[1]
    cadena = "Octal: {}".format(octal)
    partes = cadena.split(": ")
    diccionario = {partes[0].strip(): partes[1].strip()}
    return HttpResponse(json.dumps(diccionario), content_type="application/json")


    
# Convertidores de bases: a decimal
    # El constructor de los números decimales es int()
def bases_to_decimal(request, number, type):
    
    # Convertir number a entero
    if type == 'hexadecimal':
        number = int(number, 16)
    elif type == 'octal':
        number = int(number, 8)
    else:
        number = int(number, 2)
        
    cadena = "Decimal: {}".format(number)
    partes = cadena.split(": ")
    diccionario = {partes[0].strip(): partes[1].strip()}
    return HttpResponse(json.dumps(diccionario), content_type="application/json")

tarea1/patrones/views.py
import os
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import   FileSystemStorage
from django.shortcuts import redirect

from .analizador import analizador


def cargarArchivo(request):
    if request.method=='POST' and request.FILES['myfile']:
        myfile=request.FILES['myfile']
        fs=FileSystemStorage()
        file_name = myfile.name
        if fs.exists(file_name):
            # Si existe, elimina el archivo antes de guardar el nuevo
            fs.delete(file_name)
        filename = fs.save(file_name,myfile)
        file_path = fs.path(filename)
        print("La ruta del archivo subido en el servidor es:", file_path)
        return redirect(f'http://localhost:8000/patrones/resultados/{file_name}')
        
    analisis=False
    return render(request,'index.html',{'analisis':analisis, 'css':settings.STATIC_URL})




def mostrarResultados(request, nombre):
    if request.method=='POST' and request.FILES['myfile']:
        myfile=request.FILES['myfile']
        fs=FileSystemStorage()
        file_name = myfile.name
        if fs.exists(file_name):
            # Si existe, elimina el archivo antes de guardar el nuevo
            fs.delete(file_name)
        filename = fs.save(file_name,myfile)
        file_path = fs.path(filename)
        print("La ruta del archivo subido en el servidor es:", file_path)
        return redirect(f'http://localhost:8000/patrones/resultados/{file_name}')

    if request.method=='GET':
        file_path = os.path.join(settings.MEDIA_ROOT, nombre)
        direccion=str(file_path)

        resultados = analizador()
        resultados.analizar(direccion)

        dictionary = resultados.retornarResultados()
        analisis=True
        numeros=dictionary['numeros']
        numerosLetras=dictionary['numerosLetras']
        vocales=dictionary['vocales']
        caracteres=dictionary['caracteres']
    return render(request, 'index.html', {'nombreArchivo': nombre,'analisis':analisis,'numeros':numeros,'vocales':vocales,
                                            'numerosLetras':numerosLetras,'caracteres':caracteres})


def lista_archivos(request):
    
    media_root = settings.MEDIA_ROOT
    fs = FileSystemStorage(location=media_root)
    archivos = fs.listdir('')
    nombres_archivos = archivos[1]
    return render(request, 'lista-archivos.html', {'nombres_archivos': nombres_archivos})

tarea1/Conversor/templates/binario.html
<!-- HTML para el convertidor a Binario -->

{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Convertidor a Binario</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/converter.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
</head>
<body>
    <div class="tr">
        <nav class="navbar navbar-expand-lg fondoNe">
            <a class="navbar-brand fuenteNa" href="menu">Calculadora de Conversiones</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link fuenteNa" href="menu">Inicio<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fuenteNa" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Conversores
                        </a>
                        <div class="dropdown-menu fuenteN fondoNa" aria-labelledby="navbarDropdown">
                            <a onclick="redirectBinario();" class="dropdown-item" href="binario">Binario</a>
                            <a onclick="redirectHexadecimal();" class="dropdown-item" href="hexadecimal">Hexadecimal</a>
                            <a onclick="redirectOctal();" class="dropdown-item" href="octal">Octal</a>
                            <a onclick="redirectDecimal();" class="dropdown-item" href="decimal">Decimal</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fuenteNa" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Patrones
                        </a>
                        <div class="dropdown-menu fuenteN fondoNa" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'patrones:cargarArchivo' %}">Analizador</a>
                            <a class="dropdown-item" href="{% url 'patrones:listaArchivos' %}">Lista de archivos</a>
                        </div>
                    </li>
                </ul>
        
               
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="darkModeSwitch">
                    <label class="custom-control-label" for="darkModeSwitch">
                        <span id="sunIcon"><i id="darkModeIcon" class="fas fa-moon"></i></span>
                    </label>
                </div>

            </div>
        </nav>

    <div class="container my-3">
        <h1 style="text-align:center;" id="convertidorTipo">Convertir a Binario</h1>
    </div>

    
    <div class="row">
        <div class="col-3">
        </div>

        <div class="title-res container-fluid bg-dark text-center text-orange py-2 fixed-container col-6">
            <h2>Resultado</h2>
            <div id="result-screen" class="lcd-screen fixed-container" style="white-space: nowrap;">0</div>
        </div>


        <div class="col-3">
        </div>
    </div>

    <div class="container mt-5 animated-fields" id="converter-container">
        <form id="converter-form">
            <div class="form-group" id="inputTypeContainer">
                <label for="inputType" id="typeValueTxt">Tipo de Valor</label>
                <select class="form-control fondoNe fuenteNa" id="inputType" name="inputType">
                    <option value="">Seleccione un Valor</option>
                    <option value="decimal">Decimal</option>
                    <option value="octal">Octal</option>
                    <option value="hexadecimal">Hexadecimal</option>
                </select>
            </div>
            <div class="form-group " id="inputValueContainer" style="opacity: 0;">
                <label for="inputValue" id="typeValueTxt">Valor a Convertir</label>
                <input type="text" class="form-control fuenteNa fondoNe" id="inputValue" name="inputValue" placeholder="Ingrese el valor">
            </div>
            <button type="button" class="btn" id="convertButton" style="opacity: 0;">Convertir</button>
        </form>
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.8.0"></script>
    <script src="{% static 'js/Script.js' %}"></script>
</body>
</html>

tarea1/Conversor/templates/decimal.html
<!-- HTML para el convertidor a Binario -->

{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Convertidor a Decimal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/converter.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
</head>
<body>
    <div class="tr">
        <nav class="navbar navbar-expand-lg fondoNe">
            <a class="navbar-brand fuenteNa" href="menu">Calculadora de Conversiones</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link fuenteNa" href="menu">Inicio<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fuenteNa" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Conversores
                        </a>
                        <div class="dropdown-menu fuenteN fondoNa" aria-labelledby="navbarDropdown">
                            <a onclick="redirectBinario();" class="dropdown-item" href="binario">Binario</a>
                            <a onclick="redirectHexadecimal();" class="dropdown-item" href="hexadecimal">Hexadecimal</a>
                            <a onclick="redirectOctal();" class="dropdown-item" href="octal">Octal</a>
                            <a onclick="redirectDecimal();" class="dropdown-item" href="decimal">Decimal</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fuenteNa" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Patrones
                        </a>
                        <div class="dropdown-menu fuenteN fondoNa" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'patrones:cargarArchivo' %}">Analizador</a>
                            <a class="dropdown-item" href="{% url 'patrones:listaArchivos' %}">Lista de archivos</a>
                        </div>
                    </li>
                </ul>
        
               
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="darkModeSwitch">
                    <label class="custom-control-label" for="darkModeSwitch">
                        <span id="sunIcon"><i id="darkModeIcon" class="fas fa-moon"></i></span>
                    </label>
                </div>

            </div>
        </nav>
        <div class="container my-3">
            <h1 style="text-align:center;" id="convertidorTipo">Convertir a Decimal</h1>
        </div>
    
        
        <div class="row">
            <div class="col-3">
            </div>
    
            <div class="title-res container-fluid bg-dark text-center text-orange py-2 fixed-container col-6">
                <h2>Resultado</h2>
                <div id="result-screen" class="lcd-screen fixed-container" style="white-space: nowrap;">0</div>
            </div>
    
    
            <div class="col-3">
            </div>
        </div>
    
        <div class="container mt-5 animated-fields" id="converter-container">
            <form id="converter-form">
                <div class="form-group" id="inputTypeContainer">
                    <label for="inputType" id="typeValueTxt">Tipo de Valor</label>
                    <select class="form-control fondoNe fuenteNa" id="inputType" name="inputType">
                        <option value="">Seleccione un Valor</option>
                        <option value="decimal">Binario</option>
                        <option value="octal">Octal</option>
                        <option value="hexadecimal">Hexadecimal</option>
                    </select>
                </div>
                <div class="form-group " id="inputValueContainer" style="opacity: 0;">
                    <label for="inputValue" id="typeValueTxt">Valor a Convertir</label>
                    <input type="text" class="form-control fuenteNa fondoNe" id="inputValue" name="inputValue" placeholder="Ingrese el valor">
                </div>
                <button type="button" class="btn" id="convertButton" style="opacity: 0;">Convertir</button>
            </form>
        </div>
    </div>

   

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.8.0"></script>
    <script src="{% static 'js/Script.js' %}"></script>
</body>
</html>

tarea1/Conversor/templates/hexadecimal.html
<!-- HTML para el convertidor a Binario -->

{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Convertidor a Hexadecimal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/converter.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
</head>
<body>

    <div class="tr">
        <nav class="navbar navbar-expand-lg fondoNe">
            <a class="navbar-brand fuenteNa" href="menu">Calculadora de Conversiones</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link fuenteNa" href="menu">Inicio<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fuenteNa" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Conversores
                        </a>
                        <div class="dropdown-menu fuenteN fondoNa" aria-labelledby="navbarDropdown">
                            <a onclick="redirectBinario();" class="dropdown-item" href="binario">Binario</a>
                            <a onclick="redirectHexadecimal();" class="dropdown-item" href="hexadecimal">Hexadecimal</a>
                            <a onclick="redirectOctal();" class="dropdown-item" href="octal">Octal</a>
                            <a onclick="redirectDecimal();" class="dropdown-item" href="decimal">Decimal</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fuenteNa" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Patrones
                        </a>
                        <div class="dropdown-menu fuenteN fondoNa" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'patrones:cargarArchivo' %}">Analizador</a>
                            <a class="dropdown-item" href="{% url 'patrones:listaArchivos' %}">Lista de archivos</a>
                        </div>
                    </li>
                </ul>
        
               
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="darkModeSwitch">
                    <label class="custom-control-label" for="darkModeSwitch">
                        <span id="sunIcon"><i id="darkModeIcon" class="fas fa-moon"></i></span>
                    </label>
                </div>

            </div>
        </nav>
        
        
    <div class="container my-3">
        <h1 style="text-align:center;" id="convertidorTipo">Convertir a Hexadecimal</h1>
    </div>

    
    <div class="row">
        <div class="col-3">
        </div>

        <div class="title-res container-fluid bg-dark text-center text-orange py-2 fixed-container col-6">
            <h2>Resultado</h2>
            <div id="result-screen" class="lcd-screen fixed-container" style="white-space: nowrap;">0</div>
        </div>

        <div class="col-3">
        </div>
    </div>

    <div class="container mt-5 animated-fields" id="converter-container">
        <form id="converter-form">
            <div class="form-group " id="inputTypeContainer">
                <label for="inputType" id="typeValueTxt">Tipo de Valor</label>
                <select class="form-control fondoNe fuenteNa" id="inputType" name="inputType">
                    <option value="">Seleccione un Valor</option>
                    <option value="decimal">Decimal</option>
                    <option value="octal">Octal</option>
                    <option value="binario">Binario</option>
                </select>
            </div>
            <div class="form-group " id="inputValueContainer" style="opacity: 0;">
                <label for="inputValue" id="typeValueTxt">Valor a Convertir</label>
                <input type="text" class="form-control fuenteNa fondoNe" id="inputValue" name="inputValue" placeholder="Ingrese el valor">
            </div>
            <button type="button" class="btn" id="convertButton" style="opacity: 0;">Convertir</button>
        </form>
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.8.0"></script>
    <script src="{% static 'js/Script.js' %}"></script>
</body>
</html>

tarea1/patrones/templates/index.html
{% load static %}
<!DOCTYPE html>


<html>

<head>

  <title> Las aventuras de mi gato Lucky </title>

  <meta http-equiv="Content-Type" content="text / html; charset = utf-8">
  <meta name="description" content="Las aventuras de mi gato favorito Lucky, con historias, fotos y películas">
  <meta name="keywords" content="cat, Lucky, pet, animal">
  <link rel="stylesheet" href="{% static 'css/patrones.css' %}">
  
</head>

<body>
  <nav class="navBar">
    <div class="title">
      <h1>Patrones</h1>
    </div>
    <ul class="navItems">
      <li>
          <a href="/Conversor/menu">
            Inicio
          </a>
        </li>
      </li>
      <li class="drop">
        Conversiones
        <div class="dropDown">
          <a class="dropdown-item" href="{% url 'conversor:binario' %}">Binario</a>
          <a class="dropdown-item" href="{% url 'conversor:hexadecimal' %}">Hexadecimal</a>
          <a class="dropdown-item" href="{% url 'conversor:octal' %}">Octal</a>
          <a class="dropdown-item" href="{% url 'conversor:decimal' %}">Decimal</a>
        </div>
      </li>
      <li class="drop">
        Patrones
        <div class="dropDown">
          <a class="dropdown-item" href="{% url 'patrones:cargarArchivo' %}">Analizador</a>
          <a class="dropdown-item" href="{% url 'patrones:listaArchivos' %}">Lista de archivos</a>
        </div>
      </li>
    </ul>
  </nav>
  <main class="container">
    <section class="content">

      <form method="post" class="form-send" enctype="multipart/form-data" id="form">
        {% csrf_token %}
        <div id="uploadBtn" onclick="getFile()">clic para subir archivo</div>
        <div style="height: 0px; width: 0px; overflow:hidden">
          <input type="file" name="myfile" id="upFile" onchange="sub(this)">
        </div>
        <!-- <button type="submit">Subir Archivo</button> -->
      </form>
      
      {%if analisis %}

      <div class="title">Resultados del archivo {{nombreArchivo}}</div>
      <div class="bodyResults">

        <div class="artResult">
          <div class="titleResult">Secuencia de números encontrados </div>
          {% for elemento in numeros %}
          <div class="results">{{ elemento }}</div>
          {% endfor %}
        </div>

        <div class="artResult">
          <div class="titleResult">Secuencia de números seguidos de letras encontrados </div>
          {% for elemento in numerosLetras%}
          <div class="results">{{ elemento }}</div>
          {% endfor %}
        </div>
        <div class="artResult">
          <div class="titleResult">Secuencia de 3 vocales iguales encontradas </div>
          {% for elemento in vocales %}
          <div class="results">{{ elemento }}</div>
          {% endfor %}
        </div>
        <div class="artResult">
          <div class="titleResult">Secuencia de palabras con caracteres especiales </div>
          {% for elemento in caracteres %}
          <div class="results">{{ elemento }}</div>
          {% endfor %}
        </div>
        {%endif%}
        </div>
    </section>
  </main>
 <script src="{% static 'js/patrones.js' %}"></script>
</body>

</html>

tarea1/patrones/templates/lista-archivos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/patrones.css' %}">
    <title>Lista de archivos en Media</title>
</head>
<body>

    <nav class="navBar">
        <div class="title">
          <h1>Patrones</h1>
        </div>
        <ul class="navItems">
          <li>
              <a href="/Conversor/menu">
                Inicio
              </a>
            </li>
          </li>
          <li class="drop">
            Conversiones
            <div class="dropDown">
                <a class="dropdown-item" href="{% url 'conversor:binario' %}">Binario</a>
                <a class="dropdown-item" href="{% url 'conversor:hexadecimal' %}">Hexadecimal</a>
                <a class="dropdown-item" href="{% url 'conversor:octal' %}">Octal</a>
                <a class="dropdown-item" href="{% url 'conversor:decimal' %}">Decimal</a>
            </div>
          </li>
          <li class="drop">
            Patrones
            <div class="dropDown">
                <a class="dropdown-item" href="{% url 'patrones:cargarArchivo' %}">Analizador</a>
                <a class="dropdown-item" href="{% url 'patrones:listaArchivos' %}">Lista de archivos</a>
            </div>
          </li>
        </ul>
      </nav>


    <div class="container">
        <div class="content">
            <h1>Archivos en Media</h1>
            <ul class="listFiles">
                {% for nombre_archivo in nombres_archivos %}
                <li><a href="resultados/{{nombre_archivo}}">{{ nombre_archivo }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>